# Generated by Django 2.2 on 2018-10-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commens_content', models.CharField(max_length=500)),
                ('comments_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_title', models.CharField(max_length=200)),
                ('registration_text', models.CharField(max_length=5000)),
                ('pub_date', models.DateTimeField(verbose_name='Published date')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Registration'),
        ),
    ]
