# Generated by Django 2.2 on 2018-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181121_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_text',
            field=models.TextField(max_length=5000),
        ),
    ]
